# Generated by Django 5.2.1 on 2025-05-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_homepagesetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageSetting',
        ),
    ]
