# Generated by Django 5.2.1 on 2025-05-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Find Your Dream Job', max_length=200)),
                ('hero_subtitle', models.TextField(default='Connect with top employers and discover opportunities that match your skills')),
            ],
        ),
    ]
